<template>
    <div class='main-container'>
         <b-row >
            <b-col cols="12" class='margin-top' >
                <img :src="require('@/assets/quesos-grande.jpg')" alt='Pizza image' /> 
            </b-col>
        </b-row>
         <b-row >
            <b-col  sm="10" offset-sm="1"   class='title'>
                <h2>
                  <b><i>  Déjate cautivar por nuestras deliciosas pizzas 100% vegetales </i></b>
                </h2>
                <p>
                    Realizadas con masa madre y con ingredientes frescos, cocinadas en horno de leña y prepadas en el momento para ti
                </p>
                    <img class='icon bounce-top' :src="require(`@/assets/tools.png`)" alt='Menu icon'>
            </b-col>
        </b-row >
         <b-row align-v="center">
            <b-col cols md class='info'>
                <h3>
                   ¡Ven a comer con nosotros o haz tu pedido a domicilio!
                </h3>
                <p>
                   Puedes realizar <b>reservas y pedidos</b> por teléfono, en nuestro horario de apertura.<br>
                   De Martes a Domingo <br>
                   De 13:00 a 16:30 <br>
                   De 20:00 a 23:00
                </p>
            </b-col>
            <b-col cols>
               <img :src="require('@/assets/restaurant.jpg')" alt='Restaurant image' /> 
            </b-col>
        </b-row >
         <img class='icon bounce-top' :src="require(`@/assets/gorro.png`)" alt='Menu icon'>

       <b-row id='cards'>
           <b-col >
               <p>Puedes encontrarnos en</p>
                <b-card-group deck>
                        <b-card v-for="location in locations"  v-bind:key="location"   :title="location.name" :img-src="[ `${location.image}`.includes('http') ?  `${location.image}` : require(`@/assets/${location.image}`) ]" img-alt="Image" img-top>
                            <b-card-text>
                            {{location.address}}
                            </b-card-text>
                            <template v-slot:footer>
                                <small class="text-muted">{{location.phone}}</small>
                            </template>
                        </b-card>
                </b-card-group>
            </b-col>
       </b-row>
       
    </div>
</template>

<script>
import axios from 'axios';

export default {
  name: 'Content', 
  data(){
        return{       
            locations: [],
        }
    }, 
    methods: {
        getLocations(){
            const path = process.env.API_URL + '/api/locations/'

            axios.get(path).then((response) => {
                this.locations = response.data
                console.log( this.locations);
            })
            .catch((error)=>{
                console.log(error)
            })
        }  
    },
    created(){
        this.getLocations()
    }
}
</script>

<style scoped>
    #cards{
        margin: 70px 0px;
        padding: 0px 20px;
    }
    .main-container{
       font-family: 'Josefin Sans', Tahoma, sans-serif;
    }
    .title{
        padding: 70px;
    }
    .info{
        text-align:  center;
        padding: 30px;
    }
    .margin-top{
        margin-top: 56px;
    }
    img{
        width: 100%; 
    }
    h2{
        text-align: center;
    }
    .col-12{
        padding: 0px;
    }
    .icon{
        width: 60px;
        margin-top: 50px;
    }

    @media (max-width: 576px) {  
        h2{
            font-size: 25px;
        }
    }


    .bounce-top {
	    -webkit-animation: bounce-top 0.9s both;
	    animation: bounce-top 0.9s both;
    }
    
    /* ----------------------------------------------
    * Generated by Animista on 2020-5-10 11:25:4
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

    /**
    * ----------------------------------------
    * animation bounce-top
    * ----------------------------------------
    */
    @-webkit-keyframes bounce-top {
        0% {
            -webkit-transform: translateY(-45px);
                    transform: translateY(-45px);
            -webkit-animation-timing-function: ease-in;
                    animation-timing-function: ease-in;
            opacity: 1;
        }
        24% {
            opacity: 1;
        }
        40% {
            -webkit-transform: translateY(-24px);
                    transform: translateY(-24px);
            -webkit-animation-timing-function: ease-in;
                    animation-timing-function: ease-in;
        }
        65% {
            -webkit-transform: translateY(-12px);
                    transform: translateY(-12px);
            -webkit-animation-timing-function: ease-in;
                    animation-timing-function: ease-in;
        }
        82% {
            -webkit-transform: translateY(-6px);
                    transform: translateY(-6px);
            -webkit-animation-timing-function: ease-in;
                    animation-timing-function: ease-in;
        }
        93% {
            -webkit-transform: translateY(-4px);
                    transform: translateY(-4px);
            -webkit-animation-timing-function: ease-in;
                    animation-timing-function: ease-in;
        }
        25%,
        55%,
        75%,
        87% {
            -webkit-transform: translateY(0px);
                    transform: translateY(0px);
            -webkit-animation-timing-function: ease-out;
                    animation-timing-function: ease-out;
        }
        100% {
            -webkit-transform: translateY(0px);
                    transform: translateY(0px);
            -webkit-animation-timing-function: ease-out;
                    animation-timing-function: ease-out;
            opacity: 1;
        }
    }
    @keyframes bounce-top {
        0% {
            -webkit-transform: translateY(-45px);
                    transform: translateY(-45px);
            -webkit-animation-timing-function: ease-in;
                    animation-timing-function: ease-in;
            opacity: 1;
        }
        24% {
            opacity: 1;
        }
        40% {
            -webkit-transform: translateY(-24px);
                    transform: translateY(-24px);
            -webkit-animation-timing-function: ease-in;
                    animation-timing-function: ease-in;
        }
        65% {
            -webkit-transform: translateY(-12px);
                    transform: translateY(-12px);
            -webkit-animation-timing-function: ease-in;
                    animation-timing-function: ease-in;
        }
        82% {
            -webkit-transform: translateY(-6px);
                    transform: translateY(-6px);
            -webkit-animation-timing-function: ease-in;
                    animation-timing-function: ease-in;
        }
        93% {
            -webkit-transform: translateY(-4px);
                    transform: translateY(-4px);
            -webkit-animation-timing-function: ease-in;
                    animation-timing-function: ease-in;
        }
        25%,
        55%,
        75%,
        87% {
            -webkit-transform: translateY(0px);
                    transform: translateY(0px);
            -webkit-animation-timing-function: ease-out;
                    animation-timing-function: ease-out;
        }
        100% {
            -webkit-transform: translateY(0px);
                    transform: translateY(0px);
            -webkit-animation-timing-function: ease-out;
                    animation-timing-function: ease-out;
            opacity: 1;
        }
    }
</style>