# Generated by Django 3.0.6 on 2020-05-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20200507_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
