# Generated by Django 3.0.6 on 2020-05-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20200509_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('image', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
